version: '3.4'
services:

  leprikon:
    image: misli/arttep
    build: .
    depends_on:
      - mysql
      - redis
      - smtp
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: arttep
      DATABASE_USER: arttep
      DATABASE_PASSWORD: dbpassword
      EMAIL_HOST: smtp
      EMAIL_HOST_USER: arttep
      EMAIL_HOST_PASSWORD: emailpassword
      EMAIL_SUBJECT_PREFIX: '[Art-tep]'
      CACHE_LOCATION: unix:///var/run/redis/redis.sock
      SECRET_KEY: secretkey
      SENTRY_ENVIRONMENT: 'arttep'
      SERVER_EMAIL: '"Art-tep" <art-tep@leprikon.cz>'
    ports:
      - 127.0.0.1:10130:80
    volumes:
      - ./data:/app/data
      - ./media:/app/htdocs/media
      - mysql:/var/run/mysqld
      - redis:/var/run/redis

  redis:
    image: redis
    command: bash -c "chmod 0777 /var/run/redis && redis-server --appendonly yes --unixsocket /var/run/redis/redis.sock --unixsocketperm 777"
    volumes:
      - ./redis:/data
      - redis:/var/run/redis

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: arttep
      MYSQL_USER: arttep
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootdbpassword
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: leprikon.cz
      smtp_user: arttep:emailpassword
    stdin_open: true
    tty: true
    volumes:
      - ./dkim:/etc/opendkim/domainkeys

volumes:
  mysql:
  redis:
